import { Book } from '../interfaces/book.interface';

export interface CSVParseResult {
    success: Book[];
    errors: { row: number; message: string; data: any }[];
}

export const parseAndValidateCSV = (buffer: Buffer): CSVParseResult => {
    const content = buffer.toString('utf-8');
    const lines = content.split(/\r?\n/).filter((line) => line.trim() !== '');

    const success: Book[] = [];
    const errors: { row: number; message: string; data: any }[] = [];

    // Assume header exists: title,author,publishedYear
    // If no header, we might need adjustments. Let's assume header is present and we skip it.
    const headers = lines[0].split(',').map(h => h.trim().toLowerCase());

    // Basic check for headers
    if (!headers.includes('title') || !headers.includes('author') || !headers.includes('publishedyear')) {
        throw new Error('Invalid CSV headers. Expected: title, author, publishedYear');
    }

    for (let i = 1; i < lines.length; i++) {
        const line = lines[i];
        const values = line.split(','); // Simple split, doesn't handle commas in quotes

        // Create map based on headers
        const rowData: any = {};
        headers.forEach((header, index) => {
            rowData[header] = values[index]?.trim();
        });

        const { title, author, publishedyear } = rowData;

        // Validation
        const missingFields = [];
        if (!title) missingFields.push('title');
        if (!author) missingFields.push('author');
        if (!publishedyear) missingFields.push('publishedYear');

        if (missingFields.length > 0) {
            errors.push({ row: i + 1, message: `Missing fields: ${missingFields.join(', ')}`, data: rowData });
            continue;
        }

        const year = Number(publishedyear);
        if (isNaN(year)) {
            errors.push({ row: i + 1, message: 'Invalid publishedYear', data: rowData });
            continue;
        }

        // ID will be generated by service
        success.push({
            id: '', // Placeholder
            title,
            author,
            publishedYear: year,
        });
    }

    return { success, errors };
};
